### ISSUE TITLE
Adding => provisioner: ebs.csi.aws.com

### ISSUE THREAD

**Issue by kristianfzr** [sergiorua/kube-tagger#10]
Hi there,

Is it possible to add an additional provisioner option to func isEBSVolume? The EBS CSI driver is used a lot, but it lacks tagging as the kube-tagger, so if this is added it could be really useful. Could it be achieved with a simple || ?

Link to the function: https://github.com/sergiorua/kube-tagger/blob/2e587a7d5eca4aa63a61b640097d82b2d2482d88/main.go#L134

**Comment by sergiorua** [comment]
Hi!

Yes, it shouldn't be a problem. I don't have access to a EKS cluster right now. Care to send a PR? 

Thanks

**Comment by kristianfzr** [comment]
#11 

Thank you for the quick response. Im not a dev, so please have a look at the change if I messed it up by any chance!

**Comment by kristianfzr** [comment]
I will setup the EKS cluster and deploy everything during the weekend  or first thing on Tuesday and close the issue.

**Comment by kristianfzr** [comment]
@sergiorua do we need to update the tag in the helm/values.yaml file from tag: release-0.0.9 to tag: release-0.1.0 ?

**Comment by sergiorua** [comment]
I forgot, thanks. It is done now.

**Comment by kristiankanchev** [comment]
@sergiorua I see that the values file still has the old release tag 0.0.9, shouldn't it be moved to 0.1.0 ? I am having trouble to deploy the chart to EKS through terraform, but to debug it I need to make sure everything in the chart is correct as it was working prior to the change.

Error from tf: `Error: failed to fetch https://sergiorua.github.io/helm-chart/kube-tagger-3.2.0.tgz : 404 Not Found

  on modules/kube-tagger/main.tf line 1, in resource "helm_release" "kube_tagger":
   1: resource "helm_release" "kube_tagger" {


Releasing state lock. This may take a few moments...`

**Comment by kristianfzr** [comment]
@sergiorua  I see that the values file still has the old release tag 0.0.9, shouldn't it be moved to 0.1.0 ? I am having trouble to deploy the chart to EKS through terraform, but to debug it I need to make sure everything in the chart is correct as it was working prior to the change.

Error from tf: 
`Error: failed to fetch https://sergiorua.github.io/helm-chart/kube-tagger-3.2.0.tgz : 404 Not Found`

`on modules/kube-tagger/main.tf line 1, in resource "helm_release" "kube_tagger":
1: resource "helm_release" "kube_tagger" {`

`Releasing state lock. This may take a few moments...`

I even tested to install it manually and it failed:

Commands:
`
helm repo add sergiorua https://sergiorua.github.io/helm-charts/
`
`
helm upgrade --install kube-tagger sergiorua/kube-tagger
`

Output
`
history.go:56: [debug] getting history for release kube-tagger
Release "kube-tagger" does not exist. Installing it now.
install.go:173: [debug] Original chart version: ""
Error: failed to fetch https://sergiorua.github.io/helm-chart/kube-tagger-3.2.0.tgz : 404 Not Found
helm.go:81: [debug] failed to fetch https://sergiorua.github.io/helm-chart/kube-tagger-3.2.0.tgz : 404 Not Found
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get
	/private/tmp/helm-20210414-93729-197z3ms/pkg/getter/httpgetter.go:73
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get
	/private/tmp/helm-20210414-93729-197z3ms/pkg/getter/httpgetter.go:41
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	/private/tmp/helm-20210414-93729-197z3ms/pkg/downloader/chart_downloader.go:99
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	/private/tmp/helm-20210414-93729-197z3ms/pkg/action/install.go:675
main.runInstall
	/private/tmp/helm-20210414-93729-197z3ms/cmd/helm/install.go:185
main.newUpgradeCmd.func2
	/private/tmp/helm-20210414-93729-197z3ms/cmd/helm/upgrade.go:115
github.com/spf13/cobra.(*Command).execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/private/tmp/helm-20210414-93729-197z3ms/cmd/helm/helm.go:80
runtime.main
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/proc.go:225
runtime.goexit
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/asm_amd64.s:1371
`

**Comment by sergiorua** [comment]
My apologies, I don’t know what happened but the index was wrong.

Try doing a `helm repo update` and failing that remove it and add it again:

```
helm repo remove sergiorua
helm repo add sergiorua https://sergiorua.github.io/helm-charts/
```

Thanks!

**Comment by kristianfzr** [comment]
@sergiorua Now it works perfect! but it seems for some reason its not picking up the EBS as an actual EBS 2021/05/24 20:15:37 	=> Volume is not EBS.  Even after the change, maybe Im missing a part in the EBS check ?

This is the storage class:

`kind: StorageClass`
`apiVersion: storage.k8s.io/v1`
`metadata:`
  `name: ebs-sc`
`provisioner: ebs.csi.aws.com`
`volumeBindingMode: Immediate`

And this is for the PVC:

`apiVersion: v1`
`kind: PersistentVolumeClaim`
`metadata:`
  `name: ebs-claim`
  `annotations:`
    `volume.beta.kubernetes.io/additional-resource-tags: kube-tagger=true`
`spec:`
  `accessModes:`
    `- ReadWriteOnce`
  `storageClassName: ebs-sc`
  `resources:`
    `requests:`
      `storage: 4Gi`

I think I know why, the provisioner does not contain kubernetes.io/, so I think we need to make another change and remove kubernetes.io from the || or just add another || to be on the safe side only for ebs.csi.aws.com provisioner. Does that sound logical ?

**Comment by sergiorua** [comment]
I can't say for sure without testing it. I'll see if I can build a EKS cluster sometime this week and test it.

**Comment by kristianfzr** [comment]
I agree, but you will need the csi driver installed as well which will take some time to build, I can test it if you approve the merge request and let you know if this actually works if not we can revert it back. I have all the setup ready to test tomorrow :)

**Comment by kristianfzr** [comment]
@sergiorua My mistake completely the `provisioner: ebs.csi.aws.com` is what can deploy the PVC, if its set to `provisioner: kubernetes.io/ebs.csi.aws.com` it won't work. The built in for AWS is `kubernetes.io/aws-ebs` and that is why I messed it up. I did a commit on the pull request removing `kubernetes.io`.
